### ISSUE TITLE
Eldan's location needs to be corrected

### ISSUE THREAD

**Issue by keum** [cugos/cugos.github.com#121]
His location is causing map to looks too zoomed out

**Comment by mapsam** [comment]
Latitude `447.6004499`. @eldang is living on the moon!

**Comment by eldang** [comment]
Oh dear.  Give me 5 minutes and I'll return to earth....

**Comment by mapsam** [comment]
Already fixed!

**Comment by eldang** [comment]
FTW.  Thank you, and sorry about that!

**Comment by mapsam** [comment]
Definitely not a problem. Thanks for locating him, @keum!
