### ISSUE TITLE
Upcoming posts (future dated) are not showing up on cugos.org

### ISSUE THREAD

**Issue by mapsam** [cugos/cugos.github.com#142]
Thanks to a good spot from @powersa we aren't able to view "future" posts, which is important for viewing our upcoming meetings on the landing page.

I am able to reproduce this locally, and first thoughts are a jekyll API change that doesn't loop through posts in the future.

Will do some digging :hammer:

**Comment by mapsam** [comment]
Updating the `_config.yml` setting doesn't fix it for me:

```
# include future posts in our loops 
future: true
```

**Comment by mapsam** [comment]
Hmm looks like future was turned to `false` as default in https://github.com/jekyll/jekyll/commit/559cd6c7e70f96bbda7cac3d36aee13a03206a39

Running the site locally with `jekyll serve --watch --future` works great, but the config setting isn't doing anything. Hrm.

**Comment by mapsam** [comment]
Wait nevermind, `future: true` is working as expected.

**Comment by mapsam** [comment]
Confirmed this working on http://cugos.org/ :+1: 

<img width="1192" alt="screen shot 2016-02-05 at 4 46 02 pm" src="https://cloud.githubusercontent.com/assets/1943001/12863210/0664c698-cc28-11e5-9c56-02de0a3d57fa.png">

**Comment by powersa** [comment]
yeehaww!!!! :tophat: 

@mccombsp-kingco you might need to make a similar config change to http://psqgis.org/

**Comment by mccombsp-kingco** [comment]
Sam rocks. I'm just testing the change now. It fixed my problem too. Thanks to @powersa and @mapsam !!
