### ISSUE TITLE
2016 spring fling preparation

### ISSUE THREAD

**Issue by mapsam** [cugos/cugos.github.com#150]
Website updates!

### First steps

- [x] create new event page
- [x] add preliminary info
- [x] create eventbrite page for registration

### Once live

- [x] put banner on homepage (@mapsam) https://github.com/cugos/cugos.github.com/pull/152
- [x] send note to google list (?)
- [x] cugos twitter (@aaronr)
- [x] maptime twitter (@christyheaton)
- [x] personal twitters (@all)

cc/ @powersa @aaronr @christyheaton @thebigspoon @foundatron @keum

**Comment by mapsam** [comment]
Working on `fling2016` branch - have a page ready to rock, just need a new eventbrite page created and added to this page.

<img width="564" alt="screen shot 2016-02-20 at 4 37 09 pm" src="https://cloud.githubusercontent.com/assets/1943001/13200143/ac2cf3ce-d7f0-11e5-98f9-1e8c83a172d5.png">

**Comment by mapsam** [comment]
Eventbrite created at https://www.eventbrite.com/e/cugos-spring-fling-2016-tickets-21978297680

**Comment by mapsam** [comment]
I capped the registration at `120`. I don't remember what we decided as a full number so let me know if we need it changed @aaronr @powersa

**Comment by mapsam** [comment]
We are live at: http://cugos.org/2016-spring-fling/

**Comment by keum** [comment]
Well done! Sam. Looks fantastic...we capped at 150 last year but we can change it later.

**Comment by keum** [comment]
can we make the attendee list available in evenbrite?

**Comment by mapsam** [comment]
> can we make the attendee list available in evenbrite?

done @keum

**Comment by npeihl** [comment]
Woops. Sorry I closed by accident.

**Comment by keum** [comment]
sam, it would be nice to see 2016 spring fling shows up at landing page of cugos. i'm not sure how one can search for it without knowing actual url.

**Comment by mapsam** [comment]
> put banner on homepage

That's one of the tasks @keum! Want to get a :+1: from folks before making it live. Otherwise I'll get the banner put up and we should be ready to rock.

**Comment by powersa** [comment]
@mapsam this looks awesome. let's plan to make this live sometime tomorrow and coordinate with an email out to the mailing list that registration is open. Would also be good to coordinate some social media as well

**Comment by npeihl** [comment]
:+1:

**Comment by keum** [comment]
ha, jumped the gun..it pays to read more carefully...sorry. way to go!!

**Comment by aaronr** [comment]
Looks like we have 56 folks following on the cugosorg Twitter account.  Happy to blast something there tomorrow as well as on my personal twitter page.  That and the email list should hit a good number of folks.  @mapsam is kill'n it as usual... thanks man!

**Comment by mapsam** [comment]
Nice @aaronr! 

Updated the "once live" todo's to add a few more tasks for the tweets

**Comment by mapsam** [comment]
Banner PR is ready to rock. Anyone feel free to pull the trigger when we're ready for the tweet storm. https://github.com/cugos/cugos.github.com/pull/152

**Comment by keum** [comment]
woot! @mapsam is it possible to categorize the sign-in into for example public-enthuist/public agency-name/private co-name/school-affliation? something like that? in Eventbrite. i've looked and looks likey you can but not sure if you can once the event is created. thought might be useful to share the info w/ attendees and use that later for next year's when we go to the sponsor.just a thought..

**Comment by mapsam** [comment]
Initial web work is complete! Please open further tickets regarding the fling as new issues!
