### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by mapsam** [cugos/cugos.github.com#153]
We need a Code of Conduct on the spring fling page, but also something that can be used generally for the organization.

Any suggestions welcome.

**Comment by mapsam** [comment]
foss4gNA-2015: https://2016.foss4g-na.org/content/code-conduct   
state of the map: http://stateofthemap.us/codeofconduct/   
NACIS: http://nacis.org/annual-meeting/code-of-conduct/   
general conference harassment code of conduct: http://confcodeofconduct.com/

**Comment by thedeb** [comment]
This maybe the same as Foss4g.
http://www.osgeo.org/code_of_conduct

**Comment by mapsam** [comment]
Good call @thedeb - considering we are a chapter of osgeo it would make sense to use theirs.
