### ISSUE TITLE
Update DNS records for cugos.org

### ISSUE THREAD

**Issue by ranek** [cugos/cugos.github.com#230]
Per [Custom domains on GitHub Pages gain support for HTTPS](https://github.blog/2018-05-01-github-pages-custom-domains-https/) and [Setting up an apex domain](https://help.github.com/articles/setting-up-an-apex-domain/), we should update the DNS records for CUGOS.org to point to GitHub's new servers. 

There are two main benefits to this:
* Faster/more reliable serving through a CDN
* https://cugos.org/ will load over TLS without a certificate warning

I don't know who owns the domain, but it looks like it's at DreamHost, so pasting in the new IP addresses (``185.199.108.153``, ``185.199.109.153``, ``185.199.110.153``, ``185.199.111.153``) into the A record should be good. It sounds like the ``ALIAS``/``ANAME`` records might be preferred, but I don't believe DreamHost supports these.

**Comment by mapsam** [comment]
I believe @aaronr holds the keys here!

**Comment by lesserj** [comment]
@aaronr made the changes.  We are just waiting for propagation.

**Comment by lesserj** [comment]
This is done and working for me.  Cugos.org now automatically upgrades to https. Thanks @aaronr and @ranek
