### ISSUE TITLE
"Recent Google Group posts" section on front page doesn't show posts

### ISSUE THREAD

**Issue by sethvincent** [cugos/cugos.github.com#268]
It's in this file: https://github.com/cugos/cugos.github.com/blob/master/index.md

I'm not sure yet what's different about the google posts on the blog page that do show up: https://github.com/cugos/cugos.github.com/blob/master/blog/index.html#L13

**Comment by ranek** [comment]
We probably need to add the line `extra_js: /static/js/feed.js` back to the YAML front matter block. This was accidentally removed in https://github.com/cugos/cugos.github.com/commit/220cdef4d1d5ae0dbe1c0be7fe1050b61f27c884#diff-d680e8a854a7cbad6d490c445cba2eba

**Comment by keum** [comment]
thanks @ranek ... i removed that line link accidentally.  sorry :(
