### ISSUE TITLE
Dates are 1 mo behind what they really are

### ISSUE THREAD

**Issue by hallahan** [cugos/cugos.github.com#95]
Its 1, not 0

![screenshot 2015-01-07 21 22 56](https://cloud.githubusercontent.com/assets/556367/5658259/9b27f53a-96b3-11e4-89a7-30ef25d66bd5.png)

**Comment by svmatthews** [comment]
Baha - forget `getMonth()` starts at `0` instead of `1`. Will fix this.

**Comment by svmatthews** [comment]
Yeehaw. Good find @hallahan!
