### ISSUE TITLE
update the photo on the meeting page

### ISSUE THREAD

**Issue by svmatthews** [cugos/cugos.github.com#99]
The photo of @thebigspoon is actually kinda creepy. Let's update it :) http://cugos.org/meetings/ Anyone want to bring an SLR to the next meeting?

**Comment by thebigspoon** [comment]
@svmatthews: you touch that photo you are a dead man!

**Comment by hallahan** [comment]
@svmatthews, you still in town? When do you go down to SF?

**Comment by svmatthews** [comment]
Ha! I've been down in SF since the beginning of the year. You coming down for foss4g-na?

**Comment by hallahan** [comment]
Yep. Check out OpenMapKit at 

https://2015.foss4g-na.org/session/openstreetmap-survey-assessment-tools

Hope to see you there.

**Comment by svmatthews** [comment]
Schweeeeeeet! I'll be lurking with @thebigspoon most of the time so will definitely see you.

**Comment by hallahan** [comment]
@thebigspoon, you sneaking in again and sleeping in your hatchback?

**Comment by svmatthews** [comment]
@thebigspoon - your creep face has been removed!
